[package]
name = "yeet"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "throw"
path = "src/throw.rs"

[[bin]]
name = "catch"
path = "src/catch.rs"
